language: node_js

node_js:
    - "0.10"

services:
    - elasticsearch

install:
    - npm install -g grunt-cli
    - npm install

before_script:
    - sed s/trace/error/ config.json.example > config.json

script:
    - grunt travis

sudo: false
